--  INSERT INTO users (username, password, email) VALUES ('Manuel', 'Manuel123', 'manuel@gmail.com');
--  INSERT INTO users (username, password, email) VALUES ('Floriana', 'Floriana123', 'floariana@gmail.com');
--  INSERT INTO users (username, password, email) VALUES ('Santiago', 'Santiago123', 'santiago@gmail.com');
--  INSERT INTO users (username, password, email) VALUES ('IronMan', 'IronMan123', 'ironMan@gmail.com');
--  INSERT INTO users (username, password, email) VALUES ('Batman', 'Batman123', 'batman@gmail.com');
--  INSERT INTO users (username, password, email) VALUES ('DrStrange', 'DrStrange123', 'DrStrange@gmail.com');
--  INSERT INTO users (username, password, email) VALUES ('WandaM', 'WandaM123', 'WandaMaximoff@gmail.com');
--  INSERT INTO users (username, password, email) VALUES ('Spider-Man', 'SpiderMan123', 'SpiderMan@gmail.com');
--  INSERT INTO users (username, password, email) VALUES ('MilesMorales', 'MilesMorales123', 'MilesMorales@gmail.com');
--  INSERT INTO users (username, password, email) VALUES ('JamesHowlett', 'MilesMorales123', 'Wolverine@email.com');
INSERT INTO users (id,email,password,username) VALUES (1,'manuel@email.com','$2a$10$iRs5M3SWFanfYisf5ujCcecNF8Dqfeg88t/xR40KiqIwE1moQxQwG','Manuel');
INSERT INTO users (id,email,password,username) VALUES (2,'Floriana@email.com','$2a$10$ESoL6b7EgoUmnGFrWXFZoORY9tWK.bVOeYPNcxa6gJk7zWzdm3hEm','Floriana');
INSERT INTO users (id,email,password,username) VALUES (3,'Santiago@email.com','$2a$10$Kt1aqjfB/tGUaBoYvdUkv.HlCCyK9PHXPvid6Vfox9duEujLvk27a','Santiago');
INSERT INTO users (id,email,password,username) VALUES (4,'IronMan@email.com','$2a$10$ZwJaWg1LHRyvzeH4I/e6c.D9XwYGszcI5Kx8HGG.kLzFH8t4GaEX.','IronMan');
INSERT INTO users (id,email,password,username) VALUES (5,'Batman@email.com','$2a$10$6v/TIIY.ZNiTWUcP3U4WhOY9yaXXeIaV2LBedLmIeeF5SMG8XUYxa','Batman');
INSERT INTO users (id,email,password,username) VALUES (6,'DrStrange@email.com','$2a$10$qWX13Nr82xzr0jPVWtq3kOAmLSbmrO0fDApg5bruG.ixoOPVsy02O','DrStrange');
INSERT INTO users (id,email,password,username) VALUES (7,'WandaM@email.com','$2a$10$eqbJzVIu7G1jVCNHmE8HheaZOHvUi2VaGDhOx.Z/yONiUMsMvJmUe','WandaM');
INSERT INTO users (id,email,password,username) VALUES (8,'Spider-Man@email.com','$2a$10$/ab7617U2mhDtbr9/jqW4eKzpIM7cohM1J4BjUUmtOakhC6k97ATS','Spider-Man');
INSERT INTO users (id,email,password,username) VALUES (9,'MilesMorales@email.com','$2a$10$9APlU9YZlC7NFZAnBcvoIuj5cC0hC/FbSDfNFqniMUbdiA6tSJCiG','MilesMorales');
INSERT INTO users (id,email,password,username) VALUES (10,'Wolverine@email.com','$2a$10$9APlU9YZlC7NFZAnBcvoIuj5cC0hC/FbSDfNFqniMUbdiA6tSJCiG','JamesHowlett');